
heartItem:
  enabled: true
  name: '&c&lHeart'
  material: NETHER_STAR
  lore:
  - '&6Right click to gain a heart'
  addLimit: 40
  withdraw-enabled: true
  drop:
    mode: true

reviveBook:
  enabled: true
  name: '&c&lRevive Book'
  material: ENCHANTED_BOOK
  inventory-title: '&a&lRevive banned players.'
  lore:
  - '&6Revive banned players.'
  skull-lore:
  - '&aLeft click to revive that player.'
  unbreakable: false

killHeartLimit: 40
removeHeartOnlyIfKilledByPlayer: false
banOn0Hearts: true
broadcastBanFrom0Hearts: true
banTime: 0
reviveHeartAmount: 8


recipe:
  enabled: true
  recipes:
    '1':
      recipe-enabled: true
      item: extra_heart
      shaped: true
      extraHeartItemUseSuccess: 100
      discover: false
      items:
      - TOTEM_OF_UNDYING
      - DIAMOND_BLOCK
      - TOTEM_OF_UNDYING
      - DIAMOND_BLOCK
      - NETHERITE_INGOT
      - DIAMOND_BLOCK
      - TOTEM_OF_UNDYING
      - DIAMOND_BLOCK
      - TOTEM_OF_UNDYING
    '2':
      recipe-enabled: true
      item: revive_book
      shaped: true
      discover: true
      items:
      - NETHER_STAR
      - NETHERITE_INGOT
      - NETHER_STAR
      - NETHERITE_INGOT
      - ELYTRA
      - NETHERITE_INGOT
      - NETHER_STAR
      - NETHERITE_INGOT
      - NETHER_STAR


loot:
  enabled: false
  worlds:
    world:
      chanceForHeartToGenerate: 50
      heartAddChance: 50
      chanceForReviveBookToGenerate: 50
    world_nether:
      chanceForHeartToGenerate: 75
      heartAddChance: 75
      chanceForReviveBookToGenerate: 75
    world_the_end:
      chanceForHeartToGenerate: 100
      heartAddChance: 100
      chanceForReviveBookToGenerate: 100

messages:
  noMoreHeartsBan: '&c&lYou''ve lost all your hearts.'
  bannedNoMoreHeartsBroadcast: '&c&l${player} &4&lhas lost all of their hearts.'
  heartRemovedAdmin: '&4&lYou took ${amount}x hearts from ${player}.'
  heartAdded: '&a&lSomeone added ${amount}x hearts to you.'
  heartAddedAdmin: '&a&lYou added ${amount}x hearts for ${player}.'
  heartSetted: '&f&lSomeone set your hearts to ${amount}x.'
  heartSettedAdmin: '&f&lYou set the number of hearts to ${amount}x for ${player}.'
  heartCheck: '&e&l${player} has ${amount}x hearts.'
  banRemoved: '&a&lYou''ve revived ${player}.'
  playerNotFound: '&c&lPlayer not found.'
  playerNotBanned: '&c&l${player} is not banned.'
  playerNotDead: '&c&l${player} has not been eliminated, so he cannot be revived.'
  playerRevived: '&a&lYou have revived &6&l${player}&a&l!'
  maxHeartsFromExtraHeart: '&c&lYou can''t get more than ${max}x hearts.'
  heartWithdrawn: '&a&lYou''ve withdrawn a heart.'
  abuseDetected: '&c&lOur system has detected that your amount of hearts is higher
    than the maximum. We''ve reverted your hearts back to the normal value.'
  altFarmingIgnore: '&c&lOur system has detected that ${killed} is your second account
    created to farm hearts. No hearts have been added or taken away. Do you believe
    that this is a mistake? Contact server owner.'
  maxHeartsDropped: '&c&lYou have reached a heart limit. Heart earned for killing
    ${player} has been dropped.'
  heartReceived: '&a&lYou''ve received an extra heart!'
  heartGained: '&a&lYou''ve gained a heart for killing ${player}!'
  heartFailure: '&4&lYou didn''t get an extra heart.'
  heartLost: '&4&lYou''ve lost a heart.'
  heartRemoved: '&4&lSomeone has taken ${amount}x hearts from you.'
  maxHearts: '&c&lYou can''t get more than ${max}x hearts.'

placeholder-api:
  banned-text: '&c&lBanned.'
  not-banned-text: '&a&lNot Banned.'

custom-commands:
  mode: disabled
  onBan:
  - tellraw @a ${player} got banned!
  onRevive:
  - tellraw @a ${revived} got revived by ${reviving}!

security:
  alt-farming:
    ip-check: true
  limits:
    auto-revert: true
